import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"


class ScenarioLabSurfaceTests(unittest.TestCase):
    def test_enhancement_is_loaded_and_packaged_after_base_app(self):
        index = (WEB / "index.html").read_text(encoding="utf-8")
        build = (ROOT / "scripts" / "build_web.py").read_text(encoding="utf-8")

        self.assertIn('./scenario-lab.js', index)
        self.assertIn('"scenario-lab.js"', build)
        self.assertLess(index.index('./app.js'), index.index('./scenario-lab.js'))

    def test_enhancement_preserves_snapshot_and_paper_only_boundary(self):
        lab = (WEB / "scenario-lab.js").read_text(encoding="utf-8")

        self.assertIn("fetch('./report.json', { cache: 'no-store' })", lab)
        self.assertIn("candidate.schema_version !== 'desk-console-1'", lab)
        self.assertIn("candidate.report?.environment !== 'paper'", lab)
        self.assertIn("candidate.report?.live_orders_enabled !== false", lab)
        self.assertIn("scenarioRows(data.report)", lab)
        self.assertIn("Published paper snapshot only", lab)
        self.assertIn("not a live forecast", lab)
        self.assertIn("Live orders generated by Scenario Lab", lab)
        self.assertIn("does not recalculate risk, authorize a trade, or generate a live order", lab)
        self.assertNotIn("POST", lab)
        self.assertNotIn("/api/order", lab)
        self.assertNotIn("executeScenario", lab)
        self.assertNotIn("runScenario", lab)

    def test_detail_progressively_enhances_without_replacing_engine_record(self):
        lab = (WEB / "scenario-lab.js").read_text(encoding="utf-8")

        self.assertIn("What happened", lab)
        self.assertIn("Why the engine responded this way", lab)
        self.assertIn("Exact recorded inputs and outputs", lab)
        self.assertIn("JSON.stringify(scenario, null, 2)", lab)
        self.assertIn("event.stopImmediatePropagation()", lab)
        self.assertIn("data-scenario-lab-enhanced", lab)
        self.assertIn("Base Scenario Lab remains available", lab)


if __name__ == "__main__":
    unittest.main()
