import { escapeHTML as e, human, statusClass, readNotes, saveNote } from './core.mjs';
import { assessShortPut, extractShortPutRows, mrMarketContext, readFilter, readOwnIt, saveFilter, saveOwnIt } from './graham-filter.mjs';
import { mountWorkbench } from './options-workbench-ui.js';
const $ = s => document.querySelector(s);
let data, report, route='overview';
let grahamNightly=null, grahamLoading=null;
const names={'overnight-premium-desk':'Overnight Premium','earnings-event-desk':'Earnings Event','arbitrage-observer':'Box / Parity Observer','dividend-opportunity-desk':'Dividend Opportunity','open-quant-ai-model-lab':'Quant / AI Model Lab','event-futures-desk':'Futures Event'};
const layers={OBSERVED:'Observed data',STAT:'Statistical evidence',BIG:'Research proposal',DETERMINISTIC_RISK:'Deterministic risk',DETERMINISTIC_COMPLIANCE:'Compliance',HUMAN:'Human review'};
const title={overview:'Overview',dashboard:'Dashboard',candidates:'Candidates',desks:'Research desks',controls:'Controls & evidence',journal:'Yellow Sheets',resources:'Research resources',guide:'Options Guide',workbench:'Options Workbench','real-estate':'Real Estate',brief:'Daily brief',about:'About'};
const tag=s=>`<span class="tag ${statusClass(s)}">${e(human(s))}</span>`;
const money=v=>{const n=String(v);return `${n.startsWith('-')?'−':''}$${n.replace('-','').replace(/\B(?=(\d{3})+(?!\d))/g,',')}`;};
const date=v=>new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
const shortName=id=>names[id]||human(id);
const head=(t,sub,actions='')=>`<div class="page-head"><div><h1>${t}</h1><p class="subtitle">${sub}</p></div><div class="actions">${actions}</div></div>`;
const btn=(a,t,primary=false)=>`<button class="btn ${primary?'primary':''}" data-action="${a}">${t}</button>`;
const gates=p=>`<div class="gate-bars" aria-label="${e(p.layers.map(l=>`${layers[l.layer]}: ${human(l.status)}`).join('; '))}">${p.layers.map(l=>`<span class="${statusClass(l.status)}" title="${e(layers[l.layer]+': '+human(l.status))}"></span>`).join('')}</div>`;
const stat=(label,value,foot)=>`<article class="stat"><div class="eyebrow">${label}</div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></article>`;
const panel=(t,sub,body,link='')=>`<section class="panel"><div class="panel-head"><div><h2>${t}</h2>${sub?`<p>${sub}</p>`:''}</div>${link}</div>${body}</section>`;
let overviewBrief=null, overviewBriefDone=false;
async function ensureOverviewBrief(){if(overviewBriefDone)return;overviewBriefDone=true;try{const r=await fetch('./research-brief.json',{cache:'default'});if(r.ok)overviewBrief=await r.json();}catch(_){overviewBrief=null;}}
const OV_BRAND='';
function overview(){
if(typeof HedgeDeskOverview==='undefined'||!HedgeDeskOverview.render){
return OV_BRAND+'<div class="ov"><section class="ov-hero"><div class="ov-eyebrow">Overview unavailable</div><p class="ov-muted">The overview module failed to load.</p><div class="actions">'+btn('reload','Reload',true)+'</div></section></div>';
}
return OV_BRAND+HedgeDeskOverview.render(data, report, overviewBrief);
}
function brief(){return head('Daily brief','Today\u2019s research input from the six desks. Replaced every morning.',`<a class="btn" href="./research-today.md" download>↓ Full package (.md)</a>`)+
`<section class="panel" id="research-brief" aria-live="polite"><div class="panel-body"><p class="muted">Loading today\u2019s brief\u2026</p></div></section>`;}
async function hydrateBrief(){const host=document.getElementById('research-brief');if(!host)return;try{const r=await fetch('./research-brief.json',{cache:'default'});if(!r.ok)throw Error('brief unavailable');const b=await r.json();
host.innerHTML=`<div class="panel-head"><div><div class="eyebrow">${e(b.date||'')}</div><h2>${e(b.headline||'Daily research brief')}</h2></div></div><div class="panel-body">`+
(b.items||[]).map(it=>`<div class="brief-item"><h3>${e(it.title)}</h3><p>${e(it.detail)}</p></div>`).join('')+
`<details><summary>Per-desk one-liners</summary><div class="table-scroll"><table><thead><tr><th>Desk</th><th>Note</th></tr></thead><tbody>${Object.entries(b.desks||{}).map(([k,v])=>`<tr><td><strong>${e(k)}</strong></td><td>${e(v)}</td></tr>`).join('')}</tbody></table></div></details>`+
`<p class="small-note">${e(b.note||'')}</p><p><a class="text-link" href="${e(b.full_report||'./research-today.md')}" download>Download the full research package (.md) ↗</a></p></div>`;
}catch(err){host.innerHTML=`<div class="panel-body"><p class="muted">Today\u2019s brief has not been published yet. Check back after the morning research run.</p></div>`;}}
function desks(){return head('Research desks','Inspect each workflow, its evidence, and what stops the next decision.')+`<div class="cards">${report.projects.map((p,i)=>{const reg=data.registry.find(r=>r.project_id===p.project_id);return `<article class="panel desk-card"><div style="display:flex;justify-content:space-between"><span class="eyebrow">DESK 0${i+1}</span>${tag(p.disposition)}</div><h2>${e(shortName(p.project_id))}</h2><p>${e(reg.objective)}</p>${gates(p)}<button class="btn" data-desk="${p.project_id}">Open desk ↗</button></article>`}).join('')}</div>`;}
function grahamBadge(value){return `<span class="graham-badge graham-${String(value).toLowerCase().replace(/_/g,'-')}">${e(human(value))}</span>`;}
function grahamCell(row,vix){
  if(!row.grahamEligible)return '<span class="muted">Not a short put</span>';
  const ownIt=readOwnIt(localStorage,row.symbol);
  const a=assessShortPut({symbol:row.symbol,...(row.grahamMarket||{}),ownIt,vix});
  const selected=value=>ownIt===value?' selected':'';
  const metrics=a.totalMarginPct===null
    ? '<small>Awaiting nightly option data</small>'
    : `<small>MoS ${e(a.marginRating)} ${a.totalMarginPct.toFixed(2)}% · Annualized ${a.annualizedPct.toFixed(1)}% / ${a.hurdlePct.toFixed(0)}%</small>`;
  return `${grahamBadge(a.verdict)}<label class="graham-own">Own if assigned?<select class="input" data-graham-own="${e(row.symbol)}" aria-label="Would you own ${e(row.symbol)} if assigned?"><option value=""${selected(null)}>Unanswered</option><option value="yes"${selected(true)}>Yes</option><option value="no"${selected(false)}>No</option></select></label>${metrics}`;
}
function candidates(){
  const enriched=extractShortPutRows(data.candidate_feed,grahamNightly);
  const vix=grahamNightly?.vix_regime?.last_close;
  const filterOn=readFilter(localStorage);
  const assessed=enriched.map(row=>{
    if(!row.grahamEligible)return {...row,grahamAssessment:null};
    const ownIt=readOwnIt(localStorage,row.symbol);
    return {...row,grahamAssessment:assessShortPut({symbol:row.symbol,...(row.grahamMarket||{}),ownIt,vix})};
  });
  const rows=filterOn?assessed.filter(row=>row.grahamAssessment?.verdict!=='SPECULATION'):assessed;
  const market=mrMarketContext(vix);
  const marketCopy=grahamNightly
    ? `VIX ${market.vix===null?'—':market.vix.toFixed(2)} · ${e(market.read)}`
    : 'Loading real nightly VIX and short-put chain data…';
  const hidden=assessed.length-rows.length;
  return head('Research candidates','Real symbols entering your six desk methods. Graham discipline is applied inline to short puts; it does not authorize trades.',btn('export-candidates','↓ Candidate feed'))+
  `<div class="notice"><strong>Overnight candidates</strong><span>Overnight wheel candidates from the nightly batch (Yahoo/Cboe). Graham inputs use the same real nightly report.</span></div>`+
  `<div class="mr-market"><strong>MR. MARKET · ${e(market.regime)}</strong><span>${marketCopy}</span></div>`+
  `<div class="graham-toolbar"><label><input id="graham-filter-toggle" type="checkbox" ${filterOn?'checked':''}> Hide Graham speculation</label><span class="small">${hidden} filtered · NEEDS YOU remains visible</span></div>`+
  `<div class="stats">${stat('Symbols',new Set(assessed.map(r=>r.symbol)).size,'Real tickers and futures roots')}${stat('Desk assignments',assessed.length,'Shared client-neutral feed')}${stat('Short puts',assessed.filter(r=>r.grahamEligible).length,'Graham-eligible rows')}</div>`+
  panel('Six-desk candidate board','Verdict is context, not an execution gate. RoR and order flow are unchanged.',`<div class="table-scroll cards-table"><table><thead><tr><th>Symbol</th><th>Desk</th><th>Stage</th><th>Method</th><th>Graham</th><th>Evidence needed</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong class="mono">${e(r.symbol)}</strong><small>${e(human(r.instrument_type))}</small></td><td data-label="Desk">${e(shortName(r.desk_id))}</td><td data-label="Stage">${tag(r.stage)}</td><td data-label="Method">${e(r.method)}</td><td data-label="Graham" class="graham-cell">${grahamCell(r,vix)}</td><td data-label="Evidence needed">${e(r.evidence_needed)}</td></tr>`).join('')}</tbody></table></div>`);
}
async function hydrateGraham(){
  if(grahamNightly||grahamLoading)return grahamLoading;
  grahamLoading=fetch('./api/am-report',{cache:'no-store'}).then(async response=>{
    if(!response.ok)throw Error('nightly report unavailable');
    const candidate=await response.json();
    if(!candidate||typeof candidate.cash_secured_put_scan!=='object'||typeof candidate.vix_regime!=='object')throw Error('nightly Graham inputs unavailable');
    grahamNightly=candidate;
    if(route==='candidates')render();
    return candidate;
  }).catch(()=>null).finally(()=>{grahamLoading=null;});
  return grahamLoading;
}
function about(){const o=data.owner;return head('About','The builder behind Trade Desk Research.')+`<section class="panel"><div class="panel-body about-card"><div class="eyebrow">FOUNDER / BUILDER</div><h1>${e(o.display_name)}</h1><p>Trade Desk is an independent research platform built to test six specialized market approaches with reproducible evidence, with a seventh (Bonds & Rates) in development, explicit controls, and human judgment.</p><p>Research automation is separate from deterministic portfolio survival controls. Live trading and fully autonomous execution are not part of this MVP.</p><div class="actions"><a class="btn primary" href="${e(o.linkedin_url)}" target="_blank" rel="noopener noreferrer">View LinkedIn ↗</a><a class="btn" href="https://github.com/mega-byte2600/hedge-desk" target="_blank" rel="noopener noreferrer">View GitHub ↗</a></div></div></section>`+`<div class="section-gap">${panel('Access & membership','The desk is open to explore. Accounts add live data, your own broker, or an investor seat.',`<div class="table-scroll cards-table"><table><thead><tr><th>Access</th><th>What you get</th><th>How</th><th>Cost</th></tr></thead><tbody><tr><td><strong>Guest</strong><small>test drive</small></td><td data-label="What you get">Live market data across all research desks · 31-day access</td><td data-label="How">Sign in with email</td><td data-label="Cost">Free</td></tr><tr><td><strong>Member</strong><small>subscription</small></td><td data-label="What you get">Live market data · connect your own broker <em>read-only</em> · manual or automated service</td><td data-label="How">Self-serve upgrade</td><td data-label="Cost">Subscription</td></tr><tr><td><strong>LP</strong><small>investor</small></td><td data-label="What you get">Full desk service as an investor in the LLC</td><td data-label="How">Invitation from the GP</td><td data-label="Cost">Not a paid tier</td></tr></tbody></table></div><div class="panel-body"><p class="small">The public console runs on live market data from free public APIs. No synthetic fixtures are served. Members may link their own broker <strong>read-only</strong> — the desk can read positions and balances, and does not place orders. Nothing here is investment advice.</p></div>`,`<button class="btn" data-action="open-account">Sign in ↗</button>`)}</div>`;}
function kv(obj){return Object.entries(obj).map(([k,v])=>`<div class="keyvalue"><span>${e(human(k))}</span><strong>${e(typeof v==='object'?JSON.stringify(v):v)}</strong></div>`).join('')}
function openDesk(id){const p=report.projects.find(p=>p.project_id===id);if(!p)return;const reg=data.registry.find(r=>r.project_id===id);const live=p.data_status==='live';const statusEyebrow=live?'LIVE MARKET DATA':(p.data_status==='batch'?'BATCH DATA':'DATA UNAVAILABLE');const quotes=Object.values(p.live_data||{});const body=live||p.data_status==='batch'?`<div class="notice">${tag(p.data_status.toUpperCase())}<span>Base data as of ${e(date(p.data_as_of))} · ${e(p.data_source||'')}</span></div>${p.reason?`<p class="small">${e(p.reason)}</p>`:''}<div class="table-scroll cards-table"><table><thead><tr><th>Symbol</th><th>Name</th><th>Last</th><th>Change</th><th>Source</th></tr></thead><tbody>${quotes.map(q=>`<tr><td><strong>${e(q.symbol)}</strong></td><td data-label="Name">${e(q.name)}</td><td data-label="Last" class="mono">${e(q.last)}</td><td data-label="Change" class="mono">${e(q.change_pct)}%</td><td data-label="Source">${e(q.source)}</td></tr>`).join('')}</tbody></table></div>${(p.unavailable||[]).length?`<p class="small">Unavailable: ${(p.unavailable||[]).map(u=>e(u.symbol)+' — '+e(u.reason)).join('; ')}</p>`:''}`:`<div class="notice">${tag('DATA_UNAVAILABLE')}<span>${e(p.reason||'No live market data could be loaded for this desk.')}</span></div><p class="small">The desk shows data unavailable rather than synthetic fixtures. Try again shortly.</p>`;$('#detail-content').innerHTML=`<div class="dialog-head"><div><div class="eyebrow">${statusEyebrow} / ${e(date(p.evaluated_at))}</div><h2 style="margin-top:9px">${e(reg?reg.name:id)}</h2></div><button class="close" data-action="close" aria-label="Close desk">×</button></div><div class="dialog-body">${reg?`<p class="small">${e(reg.objective||'')}</p>`:''}${body}<div class="actions section-gap"><button class="btn primary" data-note-desk="${id}">Write Yellow Sheet</button><button class="btn" data-export-desk="${id}">↓ Export desk JSON</button></div></div>`;$('#detail').showModal();}
function controls(){const sources=data.research_data_sources||[];const liveDesks=(report.projects||[]).filter(p=>p.data_status==='live').length;return head('Controls & evidence','Trace the published data to its sources.',btn('export-json','↓ Export evidence'))+`<div class="stats">${stat('Desks live',liveDesks+' / '+report.projects.length,'Real market data')}${stat('Data sources',sources.length,'Free public APIs')}${stat('Synthetic data','0','None served')}${stat('Trade authorization','None','Paper research only')}</div>`+panel('Research data pipeline','Live data from free public APIs. No synthetic fixtures are served.',`<div class="table-scroll cards-table"><table><thead><tr><th>Source</th><th>Dataset</th><th>Status</th><th>Research desks</th></tr></thead><tbody>${sources.map(s=>`<tr><td>${e(human(s.source_id))}</td><td data-label="Dataset">${e(s.dataset)}</td><td data-label="Status">${tag(s.status)}</td><td data-label="Research desks">${e((s.feeds||[]).map(shortName).join(', '))}</td></tr>`).join('')}</tbody></table></div>`)+`<div class="section-gap">${panel('Report identity','Live data snapshot.',`<div class="panel-body">${kv({generated_at:report.generated_at,engine_code_commit:report.code_commit,report_type:report.report_type,runner_version:report.runner_version})}<p class="small">${report.limitations.map(e).join(' ')}</p></div>`)}</div>`;}
function notes(){try{return readNotes(localStorage)}catch{return []}}
function journal(){const ns=notes();return head('Yellow Sheets','Record the thesis, evidence, and conditions that would invalidate your research.',btn('export-notes','↓ Export notes'))+`<div class="notice"><strong>Saved in this browser</strong><span>Notes stay in this browser. Export a copy to keep them. They do not authorize trades or change engine decisions.</span></div><div class="journal-layout">${panel('New research note','A deliberate record before a decision.',`<form id="note-form" class="panel-body"><label class="form-field">Research desk<select class="input" name="desk">${report.projects.map(p=>`<option value="${p.project_id}">${e(shortName(p.project_id))}</option>`).join('')}</select></label><label class="form-field">Thesis<textarea class="input" name="thesis" maxlength="6000" required placeholder="What do you believe, and why?"></textarea></label><label class="form-field">Evidence<textarea class="input" name="evidence" maxlength="6000" required placeholder="Which observations support this thesis?"></textarea></label><label class="form-field">What would invalidate it?<textarea class="input" name="invalidation" maxlength="6000" required placeholder="Define the facts that would change your view."></textarea></label><button class="btn primary" type="submit">Save research note</button><p class="small">Bound to the currently displayed report hash.</p></form>`)}${panel('Research journal',`${ns.length} saved ${ns.length===1?'note':'notes'} in this browser`,ns.length?ns.slice().reverse().map(n=>`<article class="saved-note"><div class="eyebrow">${e(shortName(n.desk))} · ${e(date(n.created_at))}</div><p><strong>Thesis</strong><br>${e(n.thesis)}</p><details><summary>Evidence & invalidation</summary><p><strong>Evidence</strong><br>${e(n.evidence)}</p><p><strong>Invalidation</strong><br>${e(n.invalidation)}</p><p class="hash">Report: ${e(n.report_sha256)}</p></details></article>`).join(''):'<div class="empty">Your first research note starts here.</div>')}</div>`;}
function resources(){return head('Research resources','Institutional sources, market infrastructure, and selected research tools used to orient Emporion research.')+'<div class="panel"><div class="panel-body"><div class="skel-rows" aria-hidden="true"><div class="skeleton" style="height:18px;width:45%"></div><div class="skeleton" style="height:14px"></div><div class="skeleton" style="height:14px;width:82%"></div><div class="skeleton" style="height:14px;width:64%"></div></div><p class="small" role="status">Loading research resources…</p></div></div>';}
function dashSummary(){const rd=data.risk_dashboard||{};const cands=(data.candidate_feed&&data.candidate_feed.candidates)||[];const srcs=(report.data_batch&&report.data_batch.source_results)||[];const live=srcs.filter(s=>String(s.status).toUpperCase()==='PASS').length;const top=cands.slice(0,5);const acts=rd.executive_actions||[];return `<div data-dash-summary><div class="stats">`+stat('Candidates',cands.length,'Real symbols in the feed')+stat('Qualified picks',cands.filter(c=>c.stage==='REAL_EOD_CANDIDATE').length,'Method-qualified this run')+stat('Sources live',live+' / '+srcs.length,'Reporting sources')+stat('Desks evaluated',report.projects.length,'Six-desk coverage')+`</div>`+(acts.length?`<section class="panel"><div class="panel-head"><div><div class="eyebrow">WHAT NEEDS YOU</div><h2>Morning checklist</h2></div></div><div class="panel-body">`+acts.map(a=>`<p class="small">\u25b8 ${e(a)}</p>`).join('')+`</div></section>`:'')+`<div class="section-gap"><section class="panel"><div class="panel-head"><div><div class="eyebrow">TOP CANDIDATES</div><h2>First five in the feed</h2></div><a class="text-link" href="#candidates">Full board \u2197</a></div><div class="table-scroll"><table><thead><tr><th>Symbol</th><th>Desk</th><th>Stage</th></tr></thead><tbody>`+top.map(c=>`<tr><td><strong class="mono">${e(c.symbol)}</strong></td><td>${e(shortName(c.desk_id))}</td><td>${tag(c.stage)}</td></tr>`).join('')+`</tbody></table></div><div class="panel-body small">Snapshot ${e(date(report.generated_at))} \u00b7 report ${e(String((data.summary||{}).report_sha256||'').slice(0,10))}</div></section></div></div>`;}
function dashboard(){const frame='<div class="frame-shell"><div class="skeleton" aria-hidden="true"></div><iframe class="autofit-frame dash-frame" data-autofit title="Live market-data dashboard"></iframe></div>';const desktop=frame.replace('<iframe','<iframe src="/dashboard"');const mobile=`<div class="dash-mobile">${dashSummary()}<div class="section-gap"><button class="btn primary" data-action="open-full-dash" style="width:100%">Open full dashboard \u2197</button><p class="small-note">The full dashboard is a desktop-density chart wall. It loads only when you ask.</p></div><div class="frame-shell section-gap" id="dash-full" hidden><div class="skeleton" aria-hidden="true"></div><iframe class="autofit-frame dash-frame" data-autofit data-src="/dashboard" title="Live market-data dashboard"></iframe></div></div>`;return `<div class="panel"><div class="panel-head"><div><div class="eyebrow">LIVE REAL-DATA DASHBOARD</div><h2>Overnight candidates, options premium, and the wheel — on real market data.</h2></div></div>${mobile}<div class="dash-desktop">${desktop}</div></div>`;}
function workbench(){return `<div class="panel"><div class="panel-body" id="workbench-host"><p class="muted">Loading the options workbench\u2026</p></div></div>`;}
function hydrateWorkbench(){const host=document.getElementById('workbench-host');if(host)mountWorkbench(host);}
function realEstate(){return `<div class="panel"><div class="panel-body" id="real-estate-host"><p class="muted">Loading Real Estate models…</p></div></div>`;}
async function hydrateRealEstate(){
  const host=document.getElementById('real-estate-host');if(!host)return;
  try{
    if(!document.getElementById('real-estate-style')){
      const link=document.createElement('link');link.id='real-estate-style';link.rel='stylesheet';link.href='./real-estate.css?v=20261004-noir';document.head.appendChild(link);
    }
    const mod=await import('./real-estate-ui.js');
    const current=document.getElementById('real-estate-host');
    if(route!=='real-estate'||!current)return;
    current.innerHTML=mod.realEstatePage();
    mod.mountRealEstate(current);
  }catch(err){
    host.innerHTML=`<div class="error"><h2>Real Estate models unavailable</h2><p>${e(err.message||'The model UI could not load.')}</p><p>The rest of Emporion remains available.</p></div>`;
  }
}
function guide(){return `<div class="panel"><div class="panel-head"><div><div class="eyebrow">OPTIONS PREMIUM</div><h2>Selling Options Premium — visual guide.</h2></div></div><div class="frame-shell"><div class="skeleton" aria-hidden="true"></div><iframe class="autofit-frame guide-frame" data-autofit src="/guide/selling-options-premium" title="Selling options premium guide"></iframe></div></div>`;}
function fitFrame(f){try{const d=f.contentDocument;if(!d||!d.documentElement)return;const h=Math.max(d.documentElement.scrollHeight,d.body?d.body.scrollHeight:0);f.style.height=Math.max(500,h+8)+'px';}catch(_){}}
function wireFrames(){document.querySelectorAll('#main iframe[data-autofit]').forEach(f=>{if(f.dataset.wired)return;f.dataset.wired='1';f.addEventListener('load',()=>{const sk=f.previousElementSibling;if(sk&&sk.classList.contains('skeleton'))sk.style.display='none';fitFrame(f);try{new ResizeObserver(()=>fitFrame(f)).observe(f.contentDocument.documentElement);}catch(_){}});});}
let framesResizeArmed=false;
function armFramesResize(){if(framesResizeArmed)return;framesResizeArmed=true;window.addEventListener('resize',()=>{document.querySelectorAll('#main iframe[data-wired]').forEach(fitFrame);});}
async function render(){route=location.hash.slice(1)||'candidates';if(!title[route])route='candidates';document.body.dataset.route=route;document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===route);if(a.dataset.nav===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#breadcrumb').textContent=title[route];if(route==='overview')await ensureOverviewBrief();$('#main').innerHTML=({overview,dashboard,candidates,desks,controls,journal,resources,guide,workbench,'real-estate':realEstate,brief,about})[route]();if(route==='candidates')hydrateGraham();if(route==='brief')hydrateBrief();if(route==='workbench')hydrateWorkbench();if(route==='real-estate')hydrateRealEstate();wireFrames();}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Download prepared');}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
async function acceptPayload(candidate){if(candidate.schema_version!=='desk-console-1'||candidate.report?.environment!=='paper'||candidate.report.live_orders_enabled!==false||candidate.report.synthetic_data!==false||!Array.isArray(candidate.report.projects)||candidate.report.projects.length<6||!candidate.summary||!candidate.registry||candidate.candidate_feed?.schema_version!=='hedge-desk-candidates-1.0.0')throw Error('Unsupported report or paper boundary.');}
armFramesResize();
async function load(){const main=document.getElementById('main');const slow=setTimeout(()=>{if(main){const l=main.querySelector('.loading');if(l)l.textContent='Loading the overnight report…';}},2500);try{let viaApi=false,got=false;try{const response=await fetch('./api/report',{cache:'default'});if(response&&response.ok){const candidate=await response.json();await acceptPayload(candidate);data=candidate;viaApi=true;got=true}else if(response&&response.status===503){const body=await response.json().catch(()=>({}));throw Error('Data unavailable: '+(body.reason||'live market data could not be loaded.'))}}catch(err){if(!got)throw err}if(!data)throw Error('Report could not be loaded.');report=data.report;$('#reportstamp').textContent=`${viaApi?'Live engine report':'Deploy snapshot'} exported ${date(report.generated_at)}`;render();}catch(err){$('#main').innerHTML=`<div class="error"><h2>Research report unavailable</h2><p>${e(err.message)}</p><p>The console will not display decisions without its report.</p>${btn('reload','Try again')}</div>`;}finally{clearTimeout(slow);}}
document.addEventListener('click',event=>{const t=event.target.closest('button');if(!t)return;if(t.dataset.desk)openDesk(t.dataset.desk);if(t.dataset.exportDesk){const p=report.projects.find(p=>p.project_id===t.dataset.exportDesk);download(`${p.project_id}.json`,JSON.stringify({report_sha256:report.report_sha256,project:p},null,2));}if(t.dataset.noteDesk){$('#detail').close();location.hash='journal';render();$('#note-form select').value=t.dataset.noteDesk;$('#note-form textarea').focus()}switch(t.dataset.action){case 'toggle-graham':saveFilter(localStorage,!readFilter(localStorage));render();break;case 'open-full-dash':{const shell=document.getElementById('dash-full');const f=shell.querySelector('iframe');if(f&&!f.getAttribute('src'))f.setAttribute('src',f.dataset.src);shell.hidden=false;t.style.display='none';shell.scrollIntoView();break;}case 'close':$('#detail').close();break;case 'open-account':{const b=document.getElementById('acct-btn');if(b)b.click();break;}case 'reload':t.disabled=true;load();break;case 'export-json':download('trade-desk-report.json',JSON.stringify(report,null,2));break;case 'export-md':download('trade-desk-live-report.json',JSON.stringify(report,null,2));break;case 'export-notes':download('trade-desk-yellow-sheets.json',JSON.stringify(notes(),null,2));break;}});
document.addEventListener('click',event=>{const t=event.target.closest('[data-action="export-candidates"]');if(t)download('trade-desk-candidates.json',JSON.stringify(data.candidate_feed,null,2));});
document.addEventListener('change',event=>{if(event.target.id==='graham-filter-toggle'){saveFilter(localStorage,event.target.checked);render();return;}const symbol=event.target.dataset.grahamOwn;if(!symbol)return;const value=event.target.value==='yes'?true:event.target.value==='no'?false:null;saveOwnIt(localStorage,symbol,value);render();});
document.addEventListener('submit',event=>{if(event.target.id!=='note-form')return;event.preventDefault();const f=new FormData(event.target);try{saveNote(localStorage,{id:crypto.randomUUID(),created_at:new Date().toISOString(),desk:f.get('desk'),thesis:f.get('thesis'),evidence:f.get('evidence'),invalidation:f.get('invalidation'),report_sha256:report.report_sha256});render();toast('Research note saved in this browser')}catch(err){toast('Could not save note: '+err.message)}});
window.addEventListener('hashchange',()=>{if(data)render()});
load();
