import { escapeHTML as e, human, statusClass, scenarioRows, filterRows, readNotes, saveNote } from './core.mjs';
const $ = s => document.querySelector(s);
let data, report, route='overview';
const names={'overnight-premium-desk':'Overnight Premium','earnings-event-desk':'Earnings Event','arbitrage-observer':'Box / Parity Observer','dividend-opportunity-desk':'Dividend Opportunity','open-quant-ai-model-lab':'Quant / AI Model Lab','event-futures-desk':'Futures Event'};
const layers={OBSERVED:'Observed data',STAT:'Statistical evidence',BIG:'Research proposal',DETERMINISTIC_RISK:'Deterministic risk',DETERMINISTIC_COMPLIANCE:'Compliance',HUMAN:'Human review'};
const title={overview:'Overview',candidates:'Candidates',desks:'Research desks',scenarios:'Scenario lab',controls:'Controls & evidence',journal:'Yellow Sheets',about:'About'};
const tag=s=>`<span class="tag ${statusClass(s)}">${e(human(s))}</span>`;
const money=v=>{const n=String(v);return `${n.startsWith('-')?'−':''}$${n.replace('-','').replace(/\B(?=(\d{3})+(?!\d))/g,',')}`;};
const date=v=>new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
const shortName=id=>names[id]||human(id);
const head=(t,sub,actions='')=>`<div class="page-head"><div><h1>${t}</h1><p class="subtitle">${sub}</p></div><div class="actions">${actions}</div></div>`;
const btn=(a,t,primary=false)=>`<button class="btn ${primary?'primary':''}" data-action="${a}">${t}</button>`;
const gates=p=>`<div class="gate-bars" aria-label="${e(p.layers.map(l=>`${layers[l.layer]}: ${human(l.status)}`).join('; '))}">${p.layers.map(l=>`<span class="${statusClass(l.status)}" title="${e(layers[l.layer]+': '+human(l.status))}"></span>`).join('')}</div>`;
const stat=(label,value,foot)=>`<article class="stat"><div class="eyebrow">${label}</div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></article>`;
const panel=(t,sub,body,link='')=>`<section class="panel"><div class="panel-head"><div><h2>${t}</h2>${sub?`<p>${sub}</p>`:''}</div>${link}</div>${body}</section>`;
function overview(){
const s=data.summary, p=report.projects[0], m=p.layers[0].metrics;
return head('Research overview','Your desk, before the next decision.',btn('export-md','↓ Morning packet')+btn('reload','↻ Reload snapshot',true))+
`<div class="notice"><strong>REFERENCE SNAPSHOT</strong><span>Synthetic data evaluated on ${e(date(p.evaluated_at))}. This is not a current market signal.</span>${tag('PAPER_ONLY')}</div>`+
`<div class="stats">${stat('Research desks',s.projects_evaluated,'All six desk evaluations included')}${stat('Awaiting human review',s.human_review,'<span class="accent">Reference fixture only</span>')}${stat('No-trade decisions',s.no_trade_projects,'Blocked by existing desk controls')}${stat('Scenario coverage',s.war_game_scenarios,`${s.no_trade_controls} no-trade control cases`)}</div>`+
`<div class="split">${panel('Desk evaluations','Six independent research workflows',`<div class="table-scroll"><table><thead><tr><th>Research desk</th><th>Control layers</th><th>Decision</th></tr></thead><tbody>${report.projects.map((p,i)=>`<tr><td><button class="row-button desk-title" data-desk="${p.project_id}"><span class="desk-index">0${i+1}</span>${e(shortName(p.project_id))}</button></td><td>${gates(p)}</td><td>${tag(p.disposition)}</td></tr>`).join('')}</tbody></table></div><div class="panel-body" style="padding-top:0"><div class="legend"><span><i></i>Pass</span><span><i class="red"></i>Blocked</span><span><i class="gray"></i>Not required</span></div></div>`,`<a class="text-link" href="#desks">View desks ↗</a>`)}
<section class="panel focus"><div class="panel-body"><div><div class="eyebrow">IN FOCUS / SYNTHETIC FIXTURE</div><h2>Overnight<br>Premium Desk</h2><p>Defined-risk put credit spread.<br>Research complete. Human review pending.</p></div><div class="metrics"><div><label>Net credit</label><strong>${money(m.net_credit)}</strong></div><div><label>Maximum loss</label><strong>${money(m.maximum_loss)}</strong></div></div><button class="btn" data-desk="${p.project_id}">Inspect research & controls ↗</button><p class="small-note">No approval or order execution occurs in this console.</p></div></section></div>`+
`<div class="lower">${panel('Portfolio stress','Declared synthetic scenarios · not historical returns',`<div class="panel-body">${report.portfolio_stress.scenarios.map(s=>`<div class="stress-row"><span>${e(human(s.scenario_id))}</span><div class="stress-track"><span class="${Number(s.combined_net_pnl)>0?'positive':''}" style="width:${Math.max(2,Math.abs(Number(s.combined_net_pnl))/4700*100)}%"></span></div><span class="mono">${money(s.combined_net_pnl)}</span></div>`).join('')}<div class="small">Five stress cases. Values are consumed from the engine; no return forecast is implied.</div></div>`,`<a class="text-link" href="#scenarios">Explore ↗</a>`)}${panel('Operating boundary','What the current build can support',`<div class="panel-body"><div class="pipeline-line"><span>Live execution</span>${tag('DISABLED')}</div><div class="pipeline-line"><span>Real trades executed</span><strong class="mono">${report.real_trades_executed}</strong></div><div class="pipeline-line"><span>Paper reconciliation</span>${tag(s.paper_back_office_reconciliation.toUpperCase())}</div><div class="pipeline-line"><span>Data sources</span><strong>${report.data_batch.source_results.length} synthetic fixtures</strong></div><div class="pipeline-line"><span>Live release</span>${tag('BLOCKED')}</div></div>`)}</div>`;
}
function desks(){return head('Research desks','Inspect each workflow, its evidence, and what stops the next decision.')+`<div class="cards">${report.projects.map((p,i)=>{const reg=data.registry.find(r=>r.project_id===p.project_id);return `<article class="panel desk-card"><div style="display:flex;justify-content:space-between"><span class="eyebrow">DESK 0${i+1}</span>${tag(p.disposition)}</div><h2>${e(shortName(p.project_id))}</h2><p>${e(reg.objective)}</p>${gates(p)}<button class="btn" data-desk="${p.project_id}">Open desk ↗</button></article>`}).join('')}</div>`;}
function candidates(){const rows=data.candidate_feed.candidates;return head('Research candidates','Real symbols entering your six desk methods. Evidence must qualify them before they become picks.',btn('export-candidates','↓ Candidate feed'))+`<div class="notice"><strong>UNIVERSE, NOT PICKS</strong><span>Current market evidence and method scoring are not connected yet.</span>${tag('PAPER_ONLY')}</div><div class="stats">${stat('Symbols',new Set(rows.map(r=>r.symbol)).size,'Real tickers and futures roots')}${stat('Desk assignments',rows.length,'Shared client-neutral feed')}${stat('Method-qualified picks','0','Current data not connected')}${stat('Trade authorization','0','Research output only')}</div>`+panel('Six-desk candidate board','Stage and missing evidence are explicit for every symbol.',`<div class="table-scroll"><table><thead><tr><th>Symbol</th><th>Desk</th><th>Stage</th><th>Method</th><th>Evidence needed</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong class="mono">${e(r.symbol)}</strong><small>${e(human(r.instrument_type))}</small></td><td>${e(shortName(r.desk_id))}</td><td>${tag(r.stage)}</td><td>${e(r.method)}</td><td>${e(r.evidence_needed)}</td></tr>`).join('')}</tbody></table></div>`);}
function about(){const o=data.owner;return head('About','The builder behind Trade Desk Research.')+`<section class="panel"><div class="panel-body about-card"><div class="eyebrow">FOUNDER / BUILDER</div><h1>${e(o.display_name)}</h1><p>Trade Desk is an independent, paper-only research platform built to test six specialized market approaches with reproducible evidence, explicit controls, and human judgment.</p><p>Research automation is separate from deterministic portfolio survival controls. Live trading and fully autonomous execution are not part of this MVP.</p><div class="actions"><a class="btn primary" href="${e(o.linkedin_url)}" target="_blank" rel="noopener noreferrer">View LinkedIn ↗</a><a class="btn" href="https://github.com/mega-byte2600/hedge-desk" target="_blank" rel="noopener noreferrer">View GitHub ↗</a></div></div></section>`;}
function kv(obj){return Object.entries(obj).map(([k,v])=>`<div class="keyvalue"><span>${e(human(k))}</span><strong>${e(typeof v==='object'?JSON.stringify(v):v)}</strong></div>`).join('')}
function openDesk(id){const p=report.projects.find(p=>p.project_id===id);if(!p)return;const reg=data.registry.find(r=>r.project_id===id);$('#detail-content').innerHTML=`<div class="dialog-head"><div><div class="eyebrow">SYNTHETIC RESEARCH / ${e(date(p.evaluated_at))}</div><h2 style="margin-top:9px">${e(reg.name)}</h2></div><button class="close" data-action="close" aria-label="Close desk">×</button></div><div class="dialog-body"><div class="notice">${tag(p.disposition)}<span>${e(reg.objective)}</span></div><p class="small">Risk values below are immutable outputs of the existing engine. Its reference RoR model is marked unvalidated; this console does not calculate or validate RoR.</p><div class="detail-grid">${p.layers.map(l=>`<section class="gate-card"><h3>${e(layers[l.layer])} ${tag(l.status)}</h3>${l.reason_codes.map(r=>`<div class="reason">${e(r)}</div>`).join('')}${kv(l.metrics)}${l.artifact_refs.length?`<details class="evidence"><summary>${l.artifact_refs.length} evidence references</summary>${l.artifact_refs.map(a=>`<p class="hash">${e(a)}</p>`).join('')}</details>`:''}</section>`).join('')}</div><div class="actions section-gap"><button class="btn primary" data-note-desk="${id}">Write Yellow Sheet</button><button class="btn" data-export-desk="${id}">↓ Export desk JSON</button></div></div>`;$('#detail').showModal();}
function scenarios(){const groups=[...new Set(scenarioRows(report).map(s=>s.group))];return head('Scenario lab',`${data.summary.war_game_scenarios} deterministic war games plus ${data.summary.portfolio_stress_scenarios} portfolio stress cases.`,btn('export-json','↓ Full report'))+`<div class="toolbar"><input id="scenario-search" class="input" type="search" placeholder="Search scenarios or reason codes" aria-label="Search scenarios"><select id="scenario-group" class="input" aria-label="Scenario group"><option value="">All scenario groups</option>${groups.map(g=>`<option value="${e(g)}">${e(human(g))}</option>`).join('')}</select><select id="scenario-state" class="input" aria-label="Scenario decision"><option value="">All decisions</option><option value="NO_TRADE">No trade</option><option value="FREEZE_NEW_RISK">Freeze new risk</option></select></div><div class="panel"><div class="table-scroll"><table><thead><tr><th>Scenario</th><th>Group</th><th>Result</th><th>Evidence</th></tr></thead><tbody id="scenario-rows"></tbody></table></div><div id="scenario-count" class="panel-body small"></div></div>`;}
function renderScenarios(){const rows=filterRows(scenarioRows(report),$('#scenario-search').value,$('#scenario-group').value,$('#scenario-state').value);$('#scenario-rows').innerHTML=rows.map((s)=>`<tr><td><button class="row-button" data-scenario="${e(s.scenario_id)}">${e(human(s.scenario_id))}</button><small>${e(s.scenario_id)}</small></td><td>${e(human(s.group))}</td><td>${tag(s.disposition||s.lifecycle_action||'REFERENCE_RESULT')}</td><td>${(s.reason_codes||[]).length?`<span class="reason">${e(s.reason_codes[0])}</span>`:'<span class="muted">Recorded fixture result</span>'}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No scenarios match these filters.</td></tr>';$('#scenario-count').textContent=`${rows.length} scenario records shown. Select a scenario to inspect all recorded inputs and outputs.`;}
function controls(){const sources=data.research_data_sources||[];return head('Controls & evidence','Trace the published report to its sources and release requirements.',btn('export-json','↓ Export evidence'))+`<div class="stats">${stat('Source fixtures',report.data_batch.source_results.length,'Synthetic inputs only')}${stat('News adapters',sources.length,'Licensed research inputs')}${stat('Live release', 'Blocked','Existing engine decision')}${stat('Human overrides','0','Blocked gates cannot be overridden')}</div>`+panel('Research data pipeline','Adapters are code-ready; credentials and licensed payloads stay outside this public site.',`<div class="table-scroll"><table><thead><tr><th>Source</th><th>Dataset</th><th>Status</th><th>Research desks</th></tr></thead><tbody>${sources.map(s=>`<tr><td>${e(human(s.source_id))}</td><td>${e(s.dataset)}</td><td>${tag(s.status)}</td><td>${e(s.feeds.map(shortName).join(', '))}</td></tr>`).join('')}</tbody></table></div>${sources.map(s=>`<div class="panel-body"><div class="eyebrow">ENFORCED CONTROLS</div><p>${e(s.controls.join(' · '))}</p><p class="small">${e(human(s.mode))}. This source can add evidence; it cannot approve a candidate or calculate Risk of Ruin.</p></div>`).join('')}`)+`<div class="section-gap">${panel('Live release requirements','Recorded by the existing release gate',`<div class="table-scroll"><table><thead><tr><th>Requirement</th><th>Evidence status</th></tr></thead><tbody>${report.release_readiness.evidence.map(r=>`<tr><td>${e(human(r.requirement_id))}</td><td>${tag(r.satisfied?'PASS':'UNSATISFIED')}</td></tr>`).join('')}</tbody></table></div>`)}</div><div class="section-gap">${panel('Data provenance',e(report.data_batch.batch_id),`<div class="table-scroll"><table><thead><tr><th>Source</th><th>Status</th><th>Artifact SHA-256</th></tr></thead><tbody>${report.data_batch.source_results.map(s=>`<tr><td>${e(human(s.source_id))}</td><td>${tag(s.status)}</td><td class="hash">${e(s.artifact_sha256)}</td></tr>`).join('')}</tbody></table></div>`)}</div><div class="section-gap">${panel('Report identity','Publication validation runs in Python before the snapshot is exported.',`<div class="panel-body">${kv({generated_at:report.generated_at,engine_code_commit:report.code_commit,report_sha256:report.report_sha256,runner_version:report.runner_version})}<p class="small">${report.limitations.map(e).join(' ')}</p></div>`)}</div>`;}
function notes(){try{return readNotes(localStorage)}catch{return []}}
function journal(){const ns=notes();return head('Yellow Sheets','Record the thesis, evidence, and conditions that would invalidate your research.',btn('export-notes','↓ Export notes'))+`<div class="notice"><strong>BROWSER-LOCAL NOTES</strong><span>Notes stay in this browser. Export a copy to keep them. They do not authorize trades or change engine decisions.</span></div><div class="journal-layout">${panel('New research note','A deliberate record before a decision.',`<form id="note-form" class="panel-body"><label class="form-field">Research desk<select class="input" name="desk">${report.projects.map(p=>`<option value="${p.project_id}">${e(shortName(p.project_id))}</option>`).join('')}</select></label><label class="form-field">Thesis<textarea class="input" name="thesis" maxlength="6000" required placeholder="What do you believe, and why?"></textarea></label><label class="form-field">Evidence<textarea class="input" name="evidence" maxlength="6000" required placeholder="Which observations support this thesis?"></textarea></label><label class="form-field">What would invalidate it?<textarea class="input" name="invalidation" maxlength="6000" required placeholder="Define the facts that would change your view."></textarea></label><button class="btn primary" type="submit">Save research note</button><p class="small">Bound to the currently displayed report hash.</p></form>`)}${panel('Research journal',`${ns.length} saved ${ns.length===1?'note':'notes'} in this browser`,ns.length?ns.slice().reverse().map(n=>`<article class="saved-note"><div class="eyebrow">${e(shortName(n.desk))} · ${e(date(n.created_at))}</div><p><strong>Thesis</strong><br>${e(n.thesis)}</p><details><summary>Evidence & invalidation</summary><p><strong>Evidence</strong><br>${e(n.evidence)}</p><p><strong>Invalidation</strong><br>${e(n.invalidation)}</p><p class="hash">Report: ${e(n.report_sha256)}</p></details></article>`).join(''):'<div class="empty">Your first research note starts here.</div>')}</div>`;}
function render(){route=location.hash.slice(1)||'candidates';if(!title[route])route='candidates';document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===route);if(a.dataset.nav===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#breadcrumb').textContent=title[route];$('#main').innerHTML=({overview,candidates,desks,scenarios,controls,journal,about})[route]();if(route==='scenarios')renderScenarios();}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Download prepared');}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
async function load(){try{const response=await fetch('./report.json',{cache:'no-store'});if(!response.ok)throw Error('Report could not be loaded.');const candidate=await response.json();if(candidate.schema_version!=='desk-console-1'||candidate.report?.environment!=='paper'||candidate.report.live_orders_enabled!==false||!Array.isArray(candidate.report.projects)||candidate.report.projects.length!==6||!candidate.summary||!candidate.registry||candidate.candidate_feed?.schema_version!=='hedge-desk-candidates-1.0.0')throw Error('Unsupported report or paper boundary.');data=candidate;report=data.report;$('#reportstamp').textContent=`Snapshot exported ${date(report.generated_at)}`;render();}catch(err){$('#main').innerHTML=`<div class="error"><h2>Research report unavailable</h2><p>${e(err.message)}</p><p>The console will not display decisions without its report.</p>${btn('reload','Try again')}</div>`;}}
document.addEventListener('click',event=>{const t=event.target.closest('button');if(!t)return;if(t.dataset.desk)openDesk(t.dataset.desk);if(t.dataset.exportDesk){const p=report.projects.find(p=>p.project_id===t.dataset.exportDesk);download(`${p.project_id}.json`,JSON.stringify({report_sha256:report.report_sha256,project:p},null,2));}if(t.dataset.noteDesk){$('#detail').close();location.hash='journal';render();$('#note-form select').value=t.dataset.noteDesk;$('#note-form textarea').focus()}if(t.dataset.scenario){const s=scenarioRows(report).find(s=>s.scenario_id===t.dataset.scenario);$('#detail-content').innerHTML=`<div class="dialog-head"><h2>${e(human(s.scenario_id))}</h2><button class="close" data-action="close" aria-label="Close scenario">×</button></div><div class="dialog-body code-details"><p class="small">Exact engine record. Synthetic fixture only.</p><pre>${e(JSON.stringify(s,null,2))}</pre></div>`;$('#detail').showModal()}switch(t.dataset.action){case 'close':$('#detail').close();break;case 'reload':t.disabled=true;load();break;case 'export-json':download('trade-desk-report.json',JSON.stringify(report,null,2));break;case 'export-md':download('trade-desk-morning-packet.md',data.morning_markdown,'text/markdown');break;case 'export-notes':download('trade-desk-yellow-sheets.json',JSON.stringify(notes(),null,2));break;}});
document.addEventListener('click',event=>{const t=event.target.closest('[data-action="export-candidates"]');if(t)download('trade-desk-candidates.json',JSON.stringify(data.candidate_feed,null,2));});
document.addEventListener('input',event=>{if(event.target.id==='scenario-search')renderScenarios()});
document.addEventListener('change',event=>{if(['scenario-group','scenario-state'].includes(event.target.id))renderScenarios()});
document.addEventListener('submit',event=>{if(event.target.id!=='note-form')return;event.preventDefault();const f=new FormData(event.target);try{saveNote(localStorage,{id:crypto.randomUUID(),created_at:new Date().toISOString(),desk:f.get('desk'),thesis:f.get('thesis'),evidence:f.get('evidence'),invalidation:f.get('invalidation'),report_sha256:report.report_sha256});render();toast('Research note saved in this browser')}catch(err){toast('Could not save note: '+err.message)}});
window.addEventListener('hashchange',()=>{if(data)render()});
load();
