import { escapeHTML as e, human, statusClass, scenarioRows, reasonList } from './core.mjs';

let envelope = null;
let loading = null;

const tag = value => `<span class="tag ${statusClass(value)}">${e(human(value))}</span>`;
const scalarEntries = scenario => Object.entries(scenario).filter(([key, value]) =>
  !['scenario_id', 'group', 'disposition', 'lifecycle_action', 'reason_codes'].includes(key) &&
  (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
);

async function getEnvelope() {
  if (envelope) return envelope;
  if (!loading) {
    // Prefer the live endpoint: the scenario table is built from app.js's live
    // report, so reading the committed report.json snapshot here left rows whose
    // scenario_id exists live but not in the snapshot unable to resolve, which made
    // those clicks silently do nothing. report.json stays as the fallback so the
    // page still works from a static deploy.
    loading = fetch('./api/report', { cache: 'no-store' })
      .then(response => {
        if (!response.ok) throw new Error('live report unavailable');
        return response.json();
      })
      .catch(() => fetch('./report.json', { cache: 'no-store' }).then(response => {
        if (!response.ok) throw new Error('Scenario snapshot unavailable.');
        return response.json();
      }))
      .then(candidate => {
        if (candidate.schema_version !== 'desk-console-1' ||
            candidate.report?.environment !== 'paper' ||
            candidate.report?.live_orders_enabled !== false) {
          throw new Error('Unsupported scenario snapshot.');
        }
        envelope = candidate;
        return candidate;
      });
  }
  return loading;
}

let outcomes = null;
let outcomesLoading = null;

async function getOutcomes() {
  if (outcomes) return outcomes;
  if (!outcomesLoading) {
    // Real nightly paper outcomes + yellow sheets, served verbatim from the
    // committed AM report. Fail-soft: the reference war-games below still
    // render when this endpoint is unavailable.
    outcomesLoading = fetch('./api/nightly-outcomes', { cache: 'no-store' })
      .then(response => {
        if (!response.ok) throw new Error('nightly outcomes unavailable');
        return response.json();
      })
      .then(candidate => {
        if (candidate.schema_version !== 'hedge-desk-nightly-outcomes-1.0.0') {
          throw new Error('Unsupported outcomes payload.');
        }
        outcomes = candidate;
        return candidate;
      })
      .catch(() => null);
  }
  return outcomesLoading;
}

function outcomesCard(data) {
  if (!data) return '';
  const paper = data.paper_outcome_summary || {};
  const sheets = data.yellow_sheets || {};
  const entries = Number(paper.entry_count) || 0;
  const sheetCount = Number(sheets.sheet_count) || 0;
  const decisions = sheets.by_decision && typeof sheets.by_decision === 'object'
    ? Object.entries(sheets.by_decision).map(([k, v]) => `${e(human(k))}: ${e(v)}`).join(' · ')
    : '';
  const empty = entries === 0 && sheetCount === 0;
  const sha = typeof data.report_sha256 === 'string' && data.report_sha256
    ? `<div class="stat-foot">report ${e(data.report_sha256.slice(0, 12))}…</div>`
    : '';
  return `<div class="notice" data-outcomes-enhanced="true"><strong>OBSERVED PAPER OUTCOMES</strong><span>Recorded by the nightly batch from the live paper log and decision ledger — not a forecast, not a simulation.</span>${tag('PAPER_ONLY')}</div>` +
    `<div class="stats" data-outcomes-stats="true">` +
    `<article class="stat"><div class="eyebrow">Paper log entries</div><div class="stat-value">${entries}</div><div class="stat-foot">${empty ? 'No outcomes recorded yet' : 'Observed outcomes to date'}</div></article>` +
    `<article class="stat"><div class="eyebrow">Yellow sheets</div><div class="stat-value">${sheetCount}</div><div class="stat-foot">${decisions || (empty ? 'No sheets recorded yet' : 'Decision ledger')}</div></article>` +
    `<article class="stat"><div class="eyebrow">Execution boundary</div><div class="stat-value">0</div><div class="stat-foot">Live orders generated by Scenario Lab</div></article>` +
    `</div>` + (sha ? `<p class="small" style="margin-top:-8px">${sha}</p>` : '');
}

function scenarioSummary(rows) {
  const groups = new Set(rows.map(row => row.group));
  const blocked = rows.filter(row => /NO_TRADE|FREEZE/.test(row.disposition || row.lifecycle_action || '')).length;
  return `<div class="notice" data-scenario-lab-enhanced="true"><strong>REFERENCE SCENARIO SET</strong><span>Published paper snapshot only. These are recorded deterministic war games and stress cases, not a live forecast or a newly executed simulation.</span>${tag('PAPER_ONLY')}</div>` +
    `<div class="stats" data-scenario-lab-stats="true">` +
    `<article class="stat"><div class="eyebrow">Scenario records</div><div class="stat-value">${rows.length}</div><div class="stat-foot">Exact published engine outputs</div></article>` +
    `<article class="stat"><div class="eyebrow">Scenario groups</div><div class="stat-value">${groups.size}</div><div class="stat-foot">War games plus portfolio stress</div></article>` +
    `<article class="stat"><div class="eyebrow">Protective outcomes</div><div class="stat-value">${blocked}</div><div class="stat-foot">No-trade or freeze-new-risk results</div></article>` +
    `<article class="stat"><div class="eyebrow">Execution boundary</div><div class="stat-value">0</div><div class="stat-foot">Live orders generated by Scenario Lab</div></article>` +
    `</div>`;
}

async function enhanceScenarioRoute() {
  if (location.hash !== '#scenarios') return;
  const main = document.querySelector('#main');
  if (!main || main.querySelector('[data-scenario-lab-enhanced]')) return;
  try {
    const data = await getEnvelope();
    if (location.hash !== '#scenarios') return;
    const rows = scenarioRows(data.report);
    const head = main.querySelector('.page-head');
    if (head && !main.querySelector('[data-scenario-lab-enhanced]')) {
      // Real observed outcomes render above the reference war-games set.
      // The outcomes fetch is fail-soft: a missing endpoint leaves the
      // reference set exactly as it was.
      const observed = await getOutcomes();
      head.insertAdjacentHTML('afterend', outcomesCard(observed) + scenarioSummary(rows));
    }
  } catch {
    // Base Scenario Lab remains available if the progressive enhancement cannot load.
  }
}

function scenarioDetail(scenario) {
  const outcome = scenario.disposition || scenario.lifecycle_action || 'REFERENCE_RESULT';
  // scenarioRows normalises this, but this renderer can be handed a scenario from
  // elsewhere, so coerce defensively rather than throwing on a non-array.
  const reasons = reasonList(scenario.reason_codes);
  const metrics = scalarEntries(scenario).slice(0, 8);
  const metricRows = metrics.length
    ? metrics.map(([key, value]) => `<div class="keyvalue"><span>${e(human(key))}</span><strong>${e(value)}</strong></div>`).join('')
    : '<p class="small">No additional scalar inputs or outputs were recorded for this case.</p>';
  const reasonRows = reasons.length
    ? reasons.map(reason => `<div class="reason">${e(reason)}</div>`).join('')
    : '<p class="small">No reason code was recorded; inspect the exact engine record below.</p>';

  return `<div class="dialog-head"><div><div class="eyebrow">REFERENCE SCENARIO / SYNTHETIC FIXTURE</div><h2 style="margin-top:9px">${e(human(scenario.scenario_id))}</h2></div><button class="close" data-action="close" aria-label="Close scenario">×</button></div>` +
    `<div class="dialog-body"><div class="notice">${tag(outcome)}<span>${e(human(scenario.group))}. Recorded engine output; no scenario is executed from this screen.</span></div>` +
    `<div class="detail-grid"><section class="gate-card"><h3>What happened</h3>${metricRows}</section><section class="gate-card"><h3>Why the engine responded this way</h3>${reasonRows}</section></div>` +
    `<details class="evidence section-gap"><summary>Exact recorded inputs and outputs</summary><pre>${e(JSON.stringify(scenario, null, 2))}</pre></details>` +
    `<p class="small section-gap">Snapshot-driven decision support only. This view does not recalculate risk, authorize a trade, or generate a live order.</p></div>`;
}

document.addEventListener('click', async event => {
  const button = event.target.closest('button[data-scenario]');
  if (!button || location.hash !== '#scenarios') return;
  // Resolve BEFORE suppressing anything. This listener captures, and
  // stopImmediatePropagation() prevents app.js's own scenario handler (which reads
  // the live report) from running. Resolving first means that when this module
  // cannot serve the click, the event is left alone and the live handler opens the
  // dialog instead of the user getting nothing at all.
  let scenario = null;
  try {
    const data = await getEnvelope();
    scenario = scenarioRows(data.report).find(row => row.scenario_id === button.dataset.scenario);
  } catch {
    scenario = null;
  }
  if (!scenario) return;
  event.preventDefault();
  event.stopImmediatePropagation();
  const detail = document.querySelector('#detail');
  const content = document.querySelector('#detail-content');
  if (!detail || !content) return;
  content.innerHTML = scenarioDetail(scenario);
  detail.showModal();
}, true);

window.addEventListener('hashchange', () => queueMicrotask(enhanceScenarioRoute));
const observer = new MutationObserver(() => {
  if (location.hash === '#scenarios') queueMicrotask(enhanceScenarioRoute);
});
const main = document.querySelector('#main');
if (main) observer.observe(main, { childList: true });
queueMicrotask(enhanceScenarioRoute);
